spring:
  application:
    name: itoken-eureka
#  boot:
#    admin:
#      client:
#        url: http://122.51.35.224:8084
#  zipkin:
#    base-url: http://122.51.35.224:9411

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    # 表示是否将自己注册到Eureka,因为要构建集群环境，需要将自己注册到集群，所以开启
    registerWithEureka: true
    # 表示是否从Eureka获取注册信息，如果是单一节点，不炫耀同步其他的Eureka节点，则可以设置为false，但此处为集群，应该设置为true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.32.134:8761/eureka/,http://192.168.32.134:8861/eureka/,http://192.168.32.134:8961/eureka/

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health,info